# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
                ('data_req_ini', models.DateTimeField(verbose_name='data inicial')),
                ('data_req_fim', models.DateTimeField(verbose_name='data final')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=30)),
                ('servidor', models.CharField(max_length=100)),
                ('obs', models.CharField(max_length=500)),
                ('data_res_ini', models.DateTimeField(verbose_name='data inicial')),
                ('data_res_fim', models.DateTimeField(verbose_name='data final')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('nome_sol', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
