# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='solicitante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reserva.Solicitante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='atividade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reserva.Atividade'),
            preserve_default=False,
        ),
    ]
