# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0003_auto_20190503_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=30)),
                ('servidor', models.CharField(max_length=100)),
                ('obs', models.CharField(max_length=500)),
                ('data_res_ini', models.DateTimeField(verbose_name='data inicial')),
                ('data_res_fim', models.DateTimeField(verbose_name='data final')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Atividade')),
            ],
        ),
    ]
