# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20190503_1737'),
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_res_ini', models.DateTimeField(verbose_name='data inicial')),
                ('data_res_fim', models.DateTimeField(verbose_name='data final')),
                ('alunos', models.IntegerField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Atividade')),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_res_fim',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_res_ini',
        ),
    ]
